name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # this steps checks a copy of your repository
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-world-action